server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${PROJECT_SERVICE_SECURITY_USERNAME}
      password: ${PROJECT_SERVICE_SECURITY_PASSWORD}

website:
  security:
    api-key-header: ${WEBSITE_API_KEY_HEADER}
    api-key: ${WEBSITE_API_KEY}
    api-path: ${PERMITTED_PATH}

aws:
  bucket: ${AWS_PROJECTS_STAGING_BUCKET}
  service:
    base-url: https://${ALB_DNS_NAME}
company:
  service:
    base-url: https://${ALB_DNS_NAME}

cors:
  allowed-origins:
    - "https://${FRONTEND_DOMAIN}"
    - "https://${FRONTEND_SUBDOMAIN}"
    - "https://${CLOUDFRONT_DOMAIN}"
  allowed-methods:
    - GET
    - POST
    - OPTIONS

logging:
  level:
    org.springframework.security: info
