spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV:localhost}:${DB_HOST_DEV:3306}/${DB_NAME_DEV:helix_gpo_crm_projects_service}
    username: ${DB_USERNAME_DEV:root}
    password: ${DB_PASSWORD_DEV:FB6202Borussia!}
  jpa:
    hibernate:
      ddl-auto: update
