server:
  port: ${SERVER_PORT:8088}

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB
  security:
    user:
      name: ${AWS_SERVICE_SECURITY_USERNAME:user}
      password: ${AWS_SERVICE_SECURITY_PASSWORD:password}

website:
  security:
    api-key-header: ${WEBSITE_API_KEY_HEADER:WEBSITE_API_KEY_HEADER}
    api-key: ${WEBSITE_API_KEY:api-key-value}
    api-path: ${PERMITTED_PATH:/api/v1/aws/website/**}


aws:
  region: ${AWS_REGION:eu-central-1}
  access-key: ${AWS_DEV_USER_ACCESS_KEY:abc}
  secret-key: ${AWS_DEV_USER_SECRET_KEY:xyz}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:debug}
