server:
  port: ${SERVER_PORT:8088}

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB
  security:
    user:
      name: ${AWS_SERVICE_SECURITY_USERNAME:user}
      password: ${AWS_SERVICE_SECURITY_PASSWORD:password}

aws:
  region: ${AWS_REGION:eu-central-1}
  access-key: ${AWS_DEV_USER_ACCESS_KEY:AKIA3ZYW64K2QIKAEH7Z}
  secret-key: ${AWS_DEV_USER_SECRET_KEY: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}

logging:
  level:
    org.springframework.security: debug
