server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV:localhost}:${DB_HOST_DEV:3306}/${DB_NAME_DEV:helix_gpo_crm_testimonials_service}
    username: ${DB_USERNAME_DEV:root}
    password: ${DB_PASSWORD_DEV:FB6202Borussia!}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB

project:
  service:
    base-url: http://${PROJECTS_SERVICE_HOST:localhost}:${PROJECTS_SERVICE_PORT:8084}
company:
  service:
    base-url: http://${COMPANY_SERVICE_HOST:localhost}:${COMPANY_SERVICE_PORT:8086}

aws:
  region: ${AWS_REGION}
  access-key: ${AWS_DEV_USER_ACCESS_KEY}
  secret-key: ${AWS_DEV_USER_SECRET_KEY}
  bucket: ${AWS_TESTIMONIALS_DEV_BUCKET}

logging:
  level:
    org.springframework.security: debug
