server:
  port: ${SERVER_PORT:8086}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV:localhost}:${DB_HOST_DEV:3306}/${DB_NAME_DEV:helix_gpo_crm_company_service}
    username: ${DB_USERNAME_DEV:root}
    password: ${DB_PASSWORD_DEV:FB6202Borussia!}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${COMPANY_SERVICE_SECURITY_USERNAME:user}
      password: ${COMPANY_SERVICE_SECURITY_PASSWORD:password}

project:
  service:
    base-url: http://${PROJECTS_SERVICE_HOST:localhost}:${PROJECTS_SERVICE_PORT:8084}

logging:
  level:
    org.springframework.security: debug
