spring:
  application:
    name: company-service
  profiles:
    active: ${ACTIVE_SPRING_PROFILE:dev}

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-response: true
