server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV:localhost}:${DB_PORT_DEV:3306}/${DB_NAME_DEV:helix_gpo_crm_company_service}
    username: ${DB_USERNAME_DEV:root}
    password: ${DB_PASSWORD_DEV:FB6202Borussia!}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${COMPANY_SERVICE_SECURITY_USERNAME:user}
      password: ${COMPANY_SERVICE_SECURITY_PASSWORD:password}

website:
  security:
    api-key-header: ${WEBSITE_API_KEY_HEADER:WEBSITE_API_KEY_HEADER}
    api-key: ${WEBSITE_API_KEY:api-key-value}

project:
  service:
    base-url: http://${PROJECTS_SERVICE_HOST:localhost}:${PROJECTS_SERVICE_PORT:8084}

cors:
  allowed-origins:
    - "http://${FRONTEND_DEV_HOST:localhost}:${FRONTEND_DEV_PORT:4200}"
  allowed-methods:
    - GET
    - POST
    - OPTIONS

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:debug}
